### ISSUE TITLE
Frequent eviction due to low ephemeral storage limits

### ISSUE THREAD

**Issue by ctrought** [Dynatrace/dynatrace-operator#1151] opened 2022-09-14 03:29 UTC
Added in 0.8.0 via #854 the operator and webhook pods now have a hardcoded 10Mi ephemeral storage request & limit. That means once the ephemeral storage hits 10Mi it is immediately evicted.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption
![image](https://user-images.githubusercontent.com/65360454/190052310-0fde2238-89b3-49f9-a79e-2cc16281c2fe.png)

This occurs pretty regularly after upgrading to 0.8.X

<img width="924" alt="image" src="https://user-images.githubusercontent.com/65360454/190052662-a1939ca3-2e9e-4235-b71e-7f1dc54e714e.png">

Is it unexpected that the webhook pod would write 10Mi worth of data to ephemeral storage? Or perhaps the intent of the PR was only to reserve a small amount (request) and the limit should either be unset or much higher (or let the user configure it if ephemeral storage is really necessary).

**Comment by 0sewa0** [comment] 2022-09-14 08:08
duplicate of https://github.com/Dynatrace/dynatrace-operator/issues/1123

**Comment by 0sewa0** [comment] 2022-09-14 08:09
duplicate of https://github.com/Dynatrace/dynatrace-operator/issues/1123

**Closed by 0sewa0** 2022-09-14 08:09 UTC
